name: Plugin dispatch
on: 
  push:
    branches:
      main
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["enveloppe/obsidian-enveloppe"]
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ matrix.repo }}
          event-type: build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "content", "branch": "main"}'
